run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    - unused
    - typecheck
    - errcheck
    - gocritic
    - misspell
    - revive

linters-settings:
  goimports:
    local-prefixes: cloudpam
  revive:
    severity: warning
    rules:
      - name: blank-imports
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: ^web/
      linters:
        - gofmt
        - goimports

