import { useState, useCallback } from 'react'
import { post } from '../../api/client'
import type { SchemaApplyRequest, SchemaApplyResponse, SchemaPoolEntry } from '../../api/types'
import type { SchemaNode } from '../utils/cidr'

function flattenForApply(node: SchemaNode, parentRef: string | null): SchemaPoolEntry[] {
  const entry: SchemaPoolEntry = {
    ref: node.id,
    name: node.name,
    cidr: node.cidr,
    type: node.type,
    parent_ref: parentRef,
    description: 'Generated by Schema Planner',
  }

  const result: SchemaPoolEntry[] = [entry]
  for (const child of node.children) {
    result.push(...flattenForApply(child, node.id))
  }
  return result
}

export function useApplySchema() {
  const [result, setResult] = useState<SchemaApplyResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const apply = useCallback(async (schema: SchemaNode, skipConflicts = false) => {
    setLoading(true)
    setError(null)
    setResult(null)

    try {
      const pools = flattenForApply(schema, null)
      const req: SchemaApplyRequest = {
        pools,
        status: 'planned',
        tags: { schema_planner: 'true' },
        skip_conflicts: skipConflicts,
      }
      const res = await post<SchemaApplyResponse>('/api/v1/schema/apply', req)
      setResult(res)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to apply schema')
    } finally {
      setLoading(false)
    }
  }, [])

  return { result, loading, error, apply }
}
