ALTER TABLE users ADD COLUMN failed_login_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_failed_login_at TIMESTAMP;
ALTER TABLE users ADD COLUMN locked_at TIMESTAMP;
ALTER TABLE users ADD COLUMN lockout_until TIMESTAMP;
