apiVersion: v2
name: cloudpam-agent
description: CloudPAM Discovery Agent - Remote cloud resource discovery
type: application
version: 0.1.1
appVersion: "0.8.1"
keywords:
  - ipam
  - cloud
  - discovery
  - aws
home: https://github.com/BadgerOps/cloudpam
maintainers:
  - name: CloudPAM Team
    email: noreply@example.com
